### ISSUE TITLE
Release TeaBot service to all KIPAC members

### ISSUE THREAD

**Issue by yymao** [yymao/kipac-teabot#10]
All KIPAC members should be able to opt in (either by sending an email to Yao or sign up on a web interface) for TeaBot's daily paper suggestion service.

**Comment by mssgill** [comment]
@yymao - Just to be clear -- by this you mean the service that sends them papers according to their 'topic model', *not* the totally separate service where an email is being sent currently only to 3 of us (me, you, and Phil) when a paper is posted co-authored by a Kipac person, right?

**Comment by yymao** [comment]
Right --- I mean the personal recommendation service.

**Comment by yymao** [comment]
Done.
