### ISSUE TITLE
Let TeaBot subscribers set their personal preferences

### ISSUE THREAD

**Issue by yymao** [yymao/kipac-teabot#11]
Personal preferences such as email frequency, and number of papers by email.

**Comment by yipihey** [comment]
I still was hoping to be allowed to choose how many papers I get sent and whether I get abstracts, titles and whether I like the short author form or I want full author list up to x names. Having more than one author helps identify the group etc. 
 Essentially I am curious to the full arXiv but sorted according to my likely interests. So for me I'd choose only titles and full author list and ranked by interest. 
Seems like a lot to ask for... but perhaps most of these are already clear things you have to specify in the code?

**Comment by yymao** [comment]
Actually I also really want to implement this. What I have in mind is a
website which lists the arxiv entries sorted in relevance, and the users
can decide whether they want to get email notifications.

The main hold-up (other than my limited time) is to build the UI. Also, I
can't store all the data under my Stanford account, so I have to migrate
the system too. (Right now once the emails are sent, the arxiv entries are
not stored.)

As a short term workaround, maybe I can send out a full list as you
described as an email if the users want it. How do you think?

**Comment by yymao** [comment]
TeaBot now prints out up to 6 authors: 9ad78d03
A full list (up to 50 papers) sorted by relevance will be included in the email if the user requests: a0fa3220

This issue remains open because the main point of this issue is to create a web UI for users to set their own preferences.

**Comment by yymao** [comment]
A framework and some basic preference settings are implemented in 40331d33cdb6d0d7463963a78256. This issue is now closed. Additional requests of new settings should be in new issues.
