### ISSUE TITLE
Let TeaBot subscribers adjust their topic model

### ISSUE THREAD

**Issue by yymao** [yymao/kipac-teabot#12]
Let subscribers add or remove particular papers that are used in their topic model through a web interface.

**Comment by mssgill** [comment]
Agreed, would be a def step forward in what papers they want sent to them.

**Comment by yymao** [comment]
A framework and some basic settings are implemented in 40331d33cdb6d0d7463963a78256. This issue is now closed. Additional requests of new settings should be in new issues.
