### ISSUE TITLE
ascii/unicode error in find-someone

### ISSUE THREAD

**Issue by rkeisler** [yymao/kipac-teabot#14]
When trying to find somebody to read 1504.01734, I get the following error:

Error: 'ascii' codec can't encode character u'\u03b1' in position 75: ordinal not in range(128)

See http://stanford.edu/~yymao/cgi-bin/kipac-teabot/find-someone#1504.01734 .

**Comment by yymao** [comment]
Thanks for the report. This is now fixed in 5b6d0802
