### ISSUE TITLE
One paper per email, abstract as well as title, cc several people at once

### ISSUE THREAD

**Issue by drphilmarshall** [yymao/kipac-teabot#3]
The rationale is:

* Cc'ing several people might encourage email discussion of the paper
* One paper per email enables us to put the paper title in the email subject line
* To assess whether I am interested in a paper, I just want to read th eabstract without clicking away from my email
* Clicking on the link registers a vote of interest with TeaBot: I want people to vote for papers by clicking through to the PDF, not the arxiv abstract, because I want to know who has actually read the paper! (We can assume opened PDF = "read" for tea purposes ;-)

Thoughts?

**Comment by yymao** [comment]
Merged to #11.
