### ISSUE TITLE
Track arxiv posts from KIPAC people in the last 7 days, and show on a webpage

### ISSUE THREAD

**Issue by drphilmarshall** [yymao/kipac-teabot#9]
This is primarily for the blog team to choose a paper to highlight - but also for advertising on the KIPAC webpage. We'll figure out embedding frames later - main thing is to get *some* kind of web page up!
NB we need to track papers by staff and faculty as well, so we'll need these lists from Martha too.

**Comment by yymao** [comment]
The TeaBot now sends email to Mandeep and Phil if it finds new papers authored by KIPAC members. The webpage is not in the scope of TeaBot as it should be maintained separately.
